name: Build and Release LlamaServer

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build:
    name: Build and Release LlamaServer Executable
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Ensure .NET 8.0 is installed

      - name: Restore Dependencies
        run: dotnet restore LlamaServer.sln


      - name: Build Project
        run: dotnet build LlamaServer/LlamaServer.csproj -c Release

      - name: Archive Build Artifact
        run: Compress-Archive -Path LlamaServer\bin\Release\net8.0\* -DestinationPath LlamaServer-${{ github.ref_name }}-win-x64.zip
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: LlamaServer-${{ github.ref_name }}-win-x64.zip
          tag_name: ${{ github.ref_name }}
          release_name: LlamaServer ${{ github.ref_name }}
          body: "Automated release for LlamaServer version ${{ github.ref_name }} win-x64"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}